# Generated by Django 6.0.6 on 2026-06-27 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Helprequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('issue_type', models.CharField(choices=[('order', 'Order Problem'), ('payment', 'Payment Issue'), ('delivery', 'Delivery Issue'), ('login', 'Login Issue'), ('product', 'Product Issue'), ('other', 'Other')], max_length=20)),
                ('order_id', models.CharField(blank=True, max_length=50, null=True)),
                ('message', models.TextField()),
                ('status', models.CharField(default='pending', max_length=20)),
            ],
        ),
    ]
