# Generated by Django 6.0.6 on 2026-06-27 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('report_type', models.CharField(choices=[('product', 'Product Issue'), ('order', 'Order Issue'), ('payment', 'Payment Issue'), ('bug', 'Website Bug'), ('delivery', 'Delivery Issue'), ('other', 'Other')], max_length=20)),
                ('order_id', models.CharField(blank=True, max_length=50, null=True)),
                ('message', models.TextField()),
                ('status', models.CharField(default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
