# Generated by Django 6.0.6 on 2026-06-27 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_report'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='created_at',
        ),
    ]
